// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "ocrindexerweb-20181228005637-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://ocrindexerweb-20181228005637-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
